2025-05-04 20:32:17,193 ERROR: Exception on /lesson/1 [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\main\routes.py", line 130, in lesson
    return render_template('tutorials/lesson.html',
                           title=lesson.title,
                           lesson=lesson,
                           user_progress=user_progress,
                           completed=completed)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\HK4\PythonProject\app\templates\tutorials\lesson.html", line 1, in top-level template code
    {% extends "../base.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../base.html
2025-05-04 20:35:13,257 ERROR: Exception on /lesson/1 [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\main\routes.py", line 130, in lesson
    return render_template('tutorials/lesson.html',
                           title=lesson.title,
                           lesson=lesson,
                           user_progress=user_progress,
                           completed=completed)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\HK4\PythonProject\app\templates\tutorials\lesson.html", line 1, in top-level template code
    {% extends "../base.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../base.html
2025-05-04 20:36:04,103 ERROR: Exception on /lesson/1 [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\main\routes.py", line 130, in lesson
    return render_template('tutorials/lesson.html',
                           title=lesson.title,
                           lesson=lesson,
                           user_progress=user_progress,
                           completed=completed)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\HK4\PythonProject\app\templates\tutorials\lesson.html", line 1, in top-level template code
    {% extends "../base.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../base.html
2025-05-04 20:39:38,368 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:52:52,540 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
