2025-05-04 21:00:07,366 ERROR: Exception on /admin/content [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\admin\routes.py", line 22, in decorated_function
    return f(*args, **kwargs)
  File "E:\HK4\PythonProject\app\admin\routes.py", line 51, in content
    return render_template('admin/content.html', levels=levels, lessons=lessons, vocabulary=vocabulary, tests=tests)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\HK4\PythonProject\app\templates\admin\content.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\HK4\PythonProject\app\templates\base.html", line 167, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\templates\admin\content.html", line 45, in block 'content'
    {{ form.csrf_token }}
    
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-05-04 21:00:11,057 ERROR: Exception on /admin/content [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\admin\routes.py", line 22, in decorated_function
    return f(*args, **kwargs)
  File "E:\HK4\PythonProject\app\admin\routes.py", line 51, in content
    return render_template('admin/content.html', levels=levels, lessons=lessons, vocabulary=vocabulary, tests=tests)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\HK4\PythonProject\app\templates\admin\content.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\HK4\PythonProject\app\templates\base.html", line 167, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\templates\admin\content.html", line 45, in block 'content'
    {{ form.csrf_token }}
    
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-05-04 21:00:15,666 ERROR: Exception on /admin/content [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\admin\routes.py", line 22, in decorated_function
    return f(*args, **kwargs)
  File "E:\HK4\PythonProject\app\admin\routes.py", line 51, in content
    return render_template('admin/content.html', levels=levels, lessons=lessons, vocabulary=vocabulary, tests=tests)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\HK4\PythonProject\app\templates\admin\content.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\HK4\PythonProject\app\templates\base.html", line 167, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\templates\admin\content.html", line 45, in block 'content'
    {{ form.csrf_token }}
    
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
